### ISSUE TITLE
Where to put custom functions?

### ISSUE THREAD

**Issue by lornajane** [openapi-contrib/style-guides#6]
I have some rulesets to share but I have some custom functions with that, where should I put those? Are we ready to add a `functions/` directory or something?

**Comment by philsturgeon** [comment]
The answer here was a little delayed whilst I tried to get docs sorted, but the answer is: NPM modules. See a pros and cons of all the distribution methods over here: https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/guides/7-sharing-rulesets.md?group=develop

That's in the develop branch for now as we made some tweaks in order to get npm rulesets working, which is now available in v5.4.0-beta1. 

I'm going to convert this repo to a lerna-monorepo and we can maintain some awesome rulesets together, or others can use them as examples to release their own! :D
